GET http://localhost:3000/users/1

###

PATCH http://localhost:3000/users/1
Content-Type: application/json

{
    "buildingId": 1
}

###

PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "firstName": "Test",
    "lastName": "Test",
    "occupationId": 4
}

###

PUT http://localhost:3000/users/change-building/20
Content-Type: application/json

{
    "buildingId": 1
}